Pizzaslice.Client/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Pizzaslice.Client.Models;
using Pizzaslice.Data;
using Pizzaslice.Domain.Models;

namespace Pizzaslice.Client.Controllers
{
    public class LocationsController : Controller
    {
        PizzasliceDbContext _db = new PizzasliceDbContext();

        //Create locations should be a POST: from admin.
        public IActionResult CreateLocation()
        {
            var store = new Location()
            {
                LocationName = "West side",
                LocationAddress = "456 West St. Arlington TX",
                LocationZipCode = 76040
            };

            _db.Locations.Add(store);
            _db.SaveChanges();

            return RedirectToAction("ViewLocations");
        }

        //GET: /Locations/ViewLocations
        public IActionResult ViewLocations()
        {
            var locationsList = _db.Locations.ToList();
            return View(locationsList);
        }

        //GET: /Locations/ViewSelectedLocation
        public IActionResult ViewSelectedLocation(int id)
        {
            return View(_db.Locations.Single(c => c.LocationId == id));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pizzaslice.Client/Controllers/PizzasController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Pizzaslice.Client.Models;
using Pizzaslice.Domain.Models;
using Pizzaslice.Data;

namespace Pizzaslice.Client.Controllers
{
    public class PizzasController : Controller
    {
        PizzasliceDbContext _db = new PizzasliceDbContext();

        //Creating a Pizza.
        [HttpGet]
        public IActionResult CreatePizza()
        {
            return View();
        }
        //POST /Pizzas/CreatePizza
        [HttpPost]
        public IActionResult CreatePizza(Pizza pizza)
        {   
            if(ModelState.IsValid)
            {
                _db.Pizzas.Add(pizza);
                _db.SaveChanges();
            }
            return RedirectToAction("ViewPizza");
        }

        //Viewing a pizza.        
        //GET /Pizzas/ViewPizza
        public IActionResult ViewPizza()
        {   
            var pizza = _db.Pizzas.ToList();
            return View(pizza);
        }

        public ViewResult Read()
        {
            return View(_db.Pizzas.ToList());
        }
        //PUT: /Pizzas/ChangePizza
        // public IActionResult ChangePizza(int id)
        // {
        //     var res = _db.Pizzas.Single(p => p.PizzaId == id);

        //     res = crust.CrustName;
        //     res.CrustPrice = crust.CrustPrice;
        //     _db.Attach(crust);
        //     _db.SaveChanges();

        // }

        //Delete /Pizzas/DeletePizza
        public IActionResult DeletePizza(int? id) 
        {
                    
            Pizza pizza = _db.Pizzas.Find(id);
            
            return View(pizza);  

        }

        [HttpPost, ActionName("Delete")]  
        public ActionResult DeletePizza(int id)  
        {  
            Pizza pizza = _db.Pizzas.Find(id);  
            _db.Pizzas.Remove(pizza);  
            _db.SaveChanges();  
            return RedirectToAction("ViewPizza");  
        }  


        // [HttpPut]
        // public IActionResult Update(Pizza pizza)
        // {
        //     var res = _db.Pizzas.Single(p => p.PizzaId == pizza.PizzaId);

        //     res.Name = crust.CrustName;
        //     res.CrustPrice = crust.CrustPrice;
        //     _db.Attach(crust);
        //     _db.SaveChanges();

        //     //this does the same thing as above. but it does it in one move.
        //     var res1 = _db.Entry<Crust>(res);
        //     res1.State = EntityState.Modified;
        //     _db.SaveChanges();

        //     return RedirectToAction("read");
        // }

        // public IActionResult Delete(Pizza pizza)
        // {
        //     _db.Pizzas.Remove(_db.Pizzas.Single(p => p.PizzaId == pizza.PizzaId));
        //     return RedirectToAction("read");

        // }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pizzaslice.Client/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Pizzaslice.Client.Models;
using Pizzaslice.Data;
using Pizzaslice.Domain.Models;

namespace Pizzaslice.Client.Controllers
{
    public class UsersController : Controller
    {
        PizzasliceDbContext _db = new PizzasliceDbContext();
        
        //GET: Users/CreateUser
         [HttpGet]
         public IActionResult CreateUser()
         {       
           return View();
        }

        //POST: Users/CreateUser passing parameters from form.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateUser(User user)
        {                  
             if (ModelState.IsValid)
            {
                _db.Users.Add(user);
                _db.SaveChanges();
                return RedirectToAction("Read");
            }
            return RedirectToAction("CreateUser");

        }
        public ViewResult Read()
        {
            return View(_db.Users.ToList());
        }
        //GET: Users/ViewUser
        [HttpGet("{id}")]
        public IActionResult ViewUser(int id)
        {
            var user = _db.Users.Single(u => u.UserId == id);
            return View(user);
        }
        //GET: Users/Login
        [HttpGet]
        public IActionResult Login(User user)
        {                                   
            return View(user);
        }
        // [HttpPost]
        // public IActionResult Login(User user)
        // {                                 
        //     return View();
        //}
        [HttpPut]
        public IActionResult ChangeUser(int id)
        {                                 
            return View();
        }

        [HttpDelete]
        public IActionResult RemoveUser()
        {                                 
            return View();
        }
        [HttpDelete]
        public IActionResult RemoveUser(int id)
        {                                 
            return View();
        }
  

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pizzaslice.Client/Views/Users/CreateUser.cshtml
@model Pizzaslice.Domain.Models.User;

@{
    ViewBag.Title = "CreateUser";    
}

<h2>Register</h2>
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>User</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.UserEmail)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserEmail)
            @Html.ValidationMessageFor(model => model.UserEmail)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.UserPassword)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserPassword)
            @Html.ValidationMessageFor(model => model.UserPassword)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.UserZipCode)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserZipCode)
            @Html.ValidationMessageFor(model => model.UserZipCode)
        </div>

        <p>
            <input type="submit" value="CreateUser"/>
        </p>
    </fieldset>

    <div>
        <h5><a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Login</a></h5>
    </div>
}

Pizzaslice.Client/Views/Users/Login.cshtml
@model Pizzaslice.Domain.Models.User;

@{
    ViewBag.Title = "Login";    
}

<h2>Login</h2>
@using (Html.BeginForm("Login", "Users", FormMethod.Post)) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>User</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>        
        <div class="editor-label">
            @Html.LabelFor(model => model.UserPassword)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserPassword)
            @Html.ValidationMessageFor(model => model.UserPassword)
        </div> 
        <p>
            
        </p>
    </fieldset>

    <div>
        <a class="nav-link text-dark" asp-area="" asp-controller="Locations" asp-action="ViewLocations">Login</a>
    </div>
    <div>
        <h5><a class="nav-link text-dark" asp-area="" asp-controller="Pizzas" asp-action="CreatePizza">Make a Pizza!</a></h5>
    </div>
}

Pizzaslice.Client/Views/Users/Read.cshtml
@model IEnumerable<Pizzaslice.Domain.Models.User>;

<h2>Users</h2>
<table class="table">
        <tr>
            <th>@Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>@Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>@Html.DisplayNameFor(model => model.UserZipCode)
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model) {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>@Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>@Html.DisplayFor(modelItem => item.UserZipCode)
            </td>            
            <td>@Html.ActionLink("Edit", "Edit", new { id=item.UserId }) |
                @Html.ActionLink("Details", "Details", new { id=item.UserId }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.UserId })
            </td>
        </tr>
        }
    </table>

Pizzaslice.Client/Views/Users/RegisterUser.cshtml
@model Pizzaslice.Domain.Models.User;

@{
    ViewBag.Title = "RegisterUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@Model.UserId</h2>
<h2>@Model.FirstName</h2>
<h2>@Model.LastName</h2>
<h2>@Model.UserName</h2>
<h2>@Model.UserPassword</h2>
<h2>@Model.UserEmail</h2>
<h2>@Model.UserZipCode</h2>

Pizzaslice.Client/Views/Users/ViewUser.cshtml
@model Pizzaslice.Domain.Models.User;

<h2>@Model.UserId</h2>
<h2>@Model.FirstName</h2>
<h2>@Model.LastName</h2>
<h2>@Model.UserName</h2>
<h2>@Model.UserEmail</h2>
<h2>@Model.UserPassword</h2>
<h2>@Model.UserZipCode</h2>